/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.utem.musicstore;

import javax.swing.JOptionPane;
import java.io.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;
import java.text.*;
/**
 *
 * @author User
 */
public class CategoryForm extends javax.swing.JFrame {
    
    // declare object for class AddNewProduct to use methods for dealing with database
    private ConnectionData categoryCon = new ConnectionData();
    // declare object for class AddNewProduct to use methods for dealing with database
    private ConnectionData userCon = new ConnectionData();
    
    // declare object for class Item to set and get values of Item
    private Category category;
    // declare object for class Item to set and get values of Item
    private User user;
    
    private static ArrayList <Category> categoryList;
    private static ArrayList <User> userList;
    
    /**
     * Creates new form Items
     */
    public CategoryForm() {
        initComponents();
        categoryCon.ID_category();
    }
    
    // Method definition: Reset the form
    public void clearForm(){
        categoryCon.ID_category();
        txtName.setText("Enter Album Category");
        labelError.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelExit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCategory = new javax.swing.JTable();
        buttonAdd = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        buttonUpdate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        labelError = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(290, 0));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1070, 780));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelExit.setBackground(new java.awt.Color(255, 255, 255));
        labelExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelExit.setForeground(new java.awt.Color(75, 0, 130));
        labelExit.setText("X");
        labelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExitMouseClicked(evt);
            }
        });
        jPanel1.add(labelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 11, 20, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(75, 0, 130));
        jLabel1.setText("Category");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        tableCategory.setBackground(new java.awt.Color(75, 0, 130));
        tableCategory.setBorder(new javax.swing.border.MatteBorder(null));
        tableCategory.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tableCategory.setForeground(new java.awt.Color(255, 255, 255));
        tableCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ));
        tableCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCategoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCategory);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 550, 530));

        buttonAdd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonAdd.setForeground(new java.awt.Color(75, 0, 130));
        buttonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        buttonAdd.setText("Add");
        buttonAdd.setBorder(null);
        buttonAdd.setBorderPainted(false);
        buttonAdd.setIconTextGap(10);
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 110, 40));

        buttonClear.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonClear.setForeground(new java.awt.Color(75, 0, 130));
        buttonClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear.png"))); // NOI18N
        buttonClear.setText("Clear");
        buttonClear.setBorder(null);
        buttonClear.setBorderPainted(false);
        buttonClear.setIconTextGap(10);
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });
        jPanel1.add(buttonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 110, 40));

        buttonDelete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonDelete.setForeground(new java.awt.Color(75, 0, 130));
        buttonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        buttonDelete.setText("Delete");
        buttonDelete.setBorder(null);
        buttonDelete.setBorderPainted(false);
        buttonDelete.setIconTextGap(10);
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(buttonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 110, 40));

        txtID.setEditable(false);
        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtID.setForeground(new java.awt.Color(75, 0, 130));
        txtID.setText("Enter ID");
        txtID.setBorder(null);
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 250, 30));

        txtName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtName.setForeground(new java.awt.Color(75, 0, 130));
        txtName.setText("Enter Album Category");
        txtName.setBorder(null);
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 250, 30));

        buttonUpdate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonUpdate.setForeground(new java.awt.Color(75, 0, 130));
        buttonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.png"))); // NOI18N
        buttonUpdate.setText("Update");
        buttonUpdate.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        buttonUpdate.setBorderPainted(false);
        buttonUpdate.setIconTextGap(10);
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(buttonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 110, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(75, 0, 130));
        jLabel4.setText("Category");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 250, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 250, 10));

        labelError.setFont(new java.awt.Font("Segoe UI Variable", 1, 11)); // NOI18N
        labelError.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(labelError, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 260, 40));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(75, 0, 130));
        jLabel7.setText("ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseClicked
        // Close form
        setVisible(false);
    }//GEN-LAST:event_labelExitMouseClicked

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        String categoryID = txtID.getText();
        String name = txtName.getText();
        
        // Check wether the form are completed or empty
        if(!categoryID.equals("Enter ID") && !name.equals("Enter Album Category"))
        {
            JOptionPane.showMessageDialog(null, "Successfully saved.");
            category = new Category();
            
            category.setCategoryID(txtID.getText().trim());
            category.setName(txtName.getText().trim());

            // call method to update the car based on car register id
            categoryCon.updateCategory(txtID.getText().trim(), category);
            userCon.countAllSeller();

            setVisible(false);
            new CategoryForm().setVisible(true);
        }
        else
        {
            labelError.setText("Album Category Name is empty!");
        }
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        String categoryID = txtID.getText();
        String name = txtName.getText();
        
        // Check wether the form are completed or empty
        if(!categoryID.equals("Enter ID") && !name.equals("Enter Album Category"))
        {
            JOptionPane.showMessageDialog(null, "Successfully saved.");
            category = new Category();
            
            category.setCategoryID(txtID.getText().trim());
            category.setName(txtName.getText().trim());


            // call method to add
            categoryCon.addCategory(category);
            userCon.countAllSeller();
            
            categoryCon.ID_category();

            setVisible(false);
            new CategoryForm().setVisible(true);
        }
        else
        {
            labelError.setText("Album Category Name is empty!");
        }
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        String categoryID = txtID.getText();
        String name = txtName.getText();
        
        // Check wether the form are completed or empty
        if(!categoryID.equals("Enter ID") && !name.equals("Enter Album Category"))
        {
            // Display confirmation message box to delete the item
            int result = JOptionPane.showConfirmDialog(null, "Are you sure to delete the item?", "Delete Item",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (result == JOptionPane.YES_OPTION) {

                //call method to delete the category based on category number
                categoryCon.deleteCategory(txtID.getText().trim());
                userCon.countAllSeller();

                // Reset the form
                setVisible(false);
                new CategoryForm().setVisible(true);
            }
        }
        else
        {
            labelError.setText("Album Category Name is empty!");
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        // Call method to reset the form
        clearForm();
    }//GEN-LAST:event_buttonClearActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // Call method readAll() to fetch all data from database
        categoryList = categoryCon.readAllCategory();
        
        DefaultTableModel tableContent = (DefaultTableModel) tableCategory.getModel();
        
        Object rowData[] = new Object[2];
        
        // use repetition structure to read all item attributes of the ArrayList
        // and display the data in the table according to the columns and row
        for(Category x:categoryList){
            rowData[0] = x.getCategoryID();
            rowData[1] = x.getName();
            tableContent.addRow(rowData);
        }
    }//GEN-LAST:event_formComponentShown

    private void tableCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCategoryMouseClicked
        int index = tableCategory.getSelectedRow();
        TableModel model = tableCategory.getModel();
        String itemID = model.getValueAt(index, 0).toString();
        txtID.setText(itemID);
        String title = model.getValueAt(index, 1).toString();
        txtName.setText(title);
    }//GEN-LAST:event_tableCategoryMouseClicked

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        if (txtName.getText().equals("Enter Album Category"))
        {
            txtName.setText("");
        }
    }//GEN-LAST:event_txtNameFocusGained

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        if (txtName.getText().equals(""))
        {
            txtName.setText("Enter Album Category");
        }
    }//GEN-LAST:event_txtNameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CategoryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel labelExit;
    private javax.swing.JTable tableCategory;
    public static final javax.swing.JTextField txtID = new javax.swing.JTextField();
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
