/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.utem.musicstore;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.block.BlockBorder;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
/**
 *
 * @author User
 */
public class Dashboard extends javax.swing.JFrame {
    
    // declare object for class ItemManager to use methods for dealing with database
    private ConnectionData userCon = new ConnectionData();
    private ConnectionData orderCon = new ConnectionData();
    
    // declare object for class Customer to set and get values of Item
    private User user;
    
    private static ArrayList <User> userList;
    
    public String email;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }
    
    public Dashboard(String userEmail) {
        initComponents();
        userCon.countAllItems();
        userCon.countAllQuantity();
        userCon.countAllCategory();
        userCon.countAllSeller();
        userCon.countAllSales();
        //orderCon.showYear();
        orderCon.showData();
        //orderCon.showChart();
        email = userEmail;
        if(!email.equals("admin@gmail.com"))
        {
        }
        else
        {
        }
    }
    
    class jPanelGradient extends JPanel {
        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();
            
            Color color1 = new Color(0,255,255);
            Color color2 = new Color(128,0,128);
            GradientPaint gp = new GradientPaint(0,0,color1,180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
    
    class jPanelGradient2 extends JPanel {
        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();
            
            Color color1 = new Color(56, 180, 211);
            Color color2 = new Color(192,192,192);
            GradientPaint gp = new GradientPaint(0,0,color1,180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
    
    class jPanelGradient3 extends JPanel {
        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();
            
            Color color1 = new Color(56, 180, 211);
            Color color2 = new Color(255,0,255);
            GradientPaint gp = new GradientPaint(0,0,color1,180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
    
    class jPanelGradient4 extends JPanel {
        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();
            
            Color color1 = new Color(0, 225, 138);
            Color color2 = new Color(154, 255, 219);
            GradientPaint gp = new GradientPaint(0,0,color1,180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
    
    //public void showChart() {
        
        //JFreeChart showChart = ChartFactory.createLineChart("Sales", "Date", "Total", orderCon.showData(), PlotOrientation.VERTICAL, false, true, true);
        
        //CategoryPlot plot = barchart.getCategoryPlot();
        //plot.setRangeGridlinePaint(Color.black);
        //showChart.getPlot().setBackgroundPaint(Color.white);
        //showChart.getPlot().setOutlinePaint(Color.white);
        //showChart.getLegend().setBorder(BlockBorder.NONE);
        //ChartFrame chartFrm = new ChartFrame("contribution", barchart, true);
        //chartFrm.setVisible(true);
        //chartFrm.setSize(500, 400);
        
        //ChartPanel chartPanel = new ChartPanel(barchart);
        //JPanel chartPanel = new ChartPanel(showChart); 
        //jPanel8.removeAll();
        //jPanel8.add(chartPanel);
       // jPanel8.updateUI();
    //}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelItems = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelCategory = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelSellers = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelBills = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelSales = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panelLogout = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelExit = new javax.swing.JLabel();
        jPanel4 = new jPanelGradient();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new jPanelGradient2();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new jPanelGradient3();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new jPanelGradient4();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(75, 0, 130));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.setEditable(false);
        txtName.setBackground(new java.awt.Color(75, 0, 130));
        txtName.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtName.setBorder(null);
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 143, 142, -1));

        txtEmail.setEditable(false);
        txtEmail.setBackground(new java.awt.Color(75, 0, 130));
        txtEmail.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setBorder(null);
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 174, 142, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 25, -1, -1));

        panelItems.setBackground(new java.awt.Color(75, 0, 130));
        panelItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelItemsMouseClicked(evt);
            }
        });
        panelItems.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Items");
        panelItems.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 120, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CD.png"))); // NOI18N
        panelItems.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 70, 50));

        jPanel1.add(panelItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 290, 50));

        panelCategory.setBackground(new java.awt.Color(75, 0, 130));
        panelCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCategoryMouseClicked(evt);
            }
        });
        panelCategory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Category");
        panelCategory.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 120, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/category.png"))); // NOI18N
        panelCategory.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 70, 50));

        jPanel1.add(panelCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 290, 50));

        panelSellers.setBackground(new java.awt.Color(75, 0, 130));
        panelSellers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSellersMouseClicked(evt);
            }
        });
        panelSellers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Sellers");
        panelSellers.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 120, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seller.png"))); // NOI18N
        panelSellers.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 70, 50));

        jPanel1.add(panelSellers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 290, 50));

        panelBills.setBackground(new java.awt.Color(75, 0, 130));
        panelBills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBillsMouseClicked(evt);
            }
        });
        panelBills.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Bills");
        panelBills.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 120, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bills.png"))); // NOI18N
        panelBills.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 70, 50));

        jPanel1.add(panelBills, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 290, 50));

        panelSales.setBackground(new java.awt.Color(75, 0, 130));
        panelSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSalesMouseClicked(evt);
            }
        });
        panelSales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Sales Report");
        panelSales.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 120, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sales.png"))); // NOI18N
        panelSales.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 70, 50));

        jPanel1.add(panelSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 290, 50));

        panelLogout.setBackground(new java.awt.Color(75, 0, 130));
        panelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelLogoutMouseClicked(evt);
            }
        });
        panelLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Logout");
        panelLogout.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 120, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        panelLogout.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 70, 50));

        jPanel1.add(panelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 290, 50));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 780));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        labelExit.setBackground(new java.awt.Color(255, 255, 255));
        labelExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelExit.setForeground(new java.awt.Color(75, 0, 130));
        labelExit.setText("X");
        labelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExitMouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(75, 0, 130));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Items");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtItems.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        txtItems.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(txtItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 160, 50));

        txtQuantity.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtQuantity.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 80, 30));

        jPanel5.setBackground(new java.awt.Color(75, 0, 130));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Category");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtCategory.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        txtCategory.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(txtCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 160, 50));

        jPanel6.setBackground(new java.awt.Color(75, 0, 130));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Sellers");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtSellers.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        txtSellers.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(txtSellers, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 160, 50));

        jPanel7.setBackground(new java.awt.Color(75, 0, 130));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Total");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtTotal.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 160, 50));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(75, 0, 130));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Top 3 Items");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pieChart1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labelExit)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pieChart1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 1080, 780));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Do you want to close Application", "Select", JOptionPane. YES_NO_OPTION);
        if (a == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_labelExitMouseClicked

    private void panelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogoutMouseClicked
        int a = JOptionPane.showConfirmDialog(null,"Do you want to logout?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_panelLogoutMouseClicked

    private void panelItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelItemsMouseClicked
        new ItemsForm().setVisible(true);
    }//GEN-LAST:event_panelItemsMouseClicked

    private void panelCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCategoryMouseClicked
        new CategoryForm().setVisible(true);
    }//GEN-LAST:event_panelCategoryMouseClicked

    private void panelSellersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSellersMouseClicked
        new SellersForm().setVisible(true);
    }//GEN-LAST:event_panelSellersMouseClicked

    private void panelBillsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBillsMouseClicked
        new BillForm().setVisible(true);
    }//GEN-LAST:event_panelBillsMouseClicked

    private void panelSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSalesMouseClicked
        new ReportForm().setVisible(true);
    }//GEN-LAST:event_panelSalesMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //orderCon.showData();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel labelExit;
    private javax.swing.JPanel panelBills;
    private javax.swing.JPanel panelCategory;
    private javax.swing.JPanel panelItems;
    private javax.swing.JPanel panelLogout;
    private javax.swing.JPanel panelSales;
    private javax.swing.JPanel panelSellers;
    public static final com.utem.musicstore.PieChart pieChart1 = new com.utem.musicstore.PieChart();
    public static final javax.swing.JLabel txtCategory = new javax.swing.JLabel();
    public static final javax.swing.JTextField txtEmail = new javax.swing.JTextField();
    public static final javax.swing.JLabel txtItems = new javax.swing.JLabel();
    public static final javax.swing.JTextField txtName = new javax.swing.JTextField();
    public static final javax.swing.JLabel txtQuantity = new javax.swing.JLabel();
    public static final javax.swing.JLabel txtSellers = new javax.swing.JLabel();
    public static final javax.swing.JLabel txtTotal = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
