/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.utem.musicstore;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.io.*;
import java.util.*;
import javax.swing.*;
import javax.swing.Timer;
import javax.swing.table.*;
import java.text.*;
/**
 *
 * @author User
 */
public class OrderForm extends javax.swing.JFrame {
    
    // declare object for class ItemManager to use methods for dealing with database
    private ConnectionData userCon = new ConnectionData();
    // declare object for class AddNewProduct to use methods for dealing with database
    private ConnectionData itemsCon = new ConnectionData();
    // declare object for class AddNewProduct to use methods for dealing with database
    private ConnectionData categoryCon = new ConnectionData();
    // declare object for class AddNewProduct to use methods for dealing with database
    private ConnectionData orderCon = new ConnectionData();
    // declare object for class AddNewProduct to use methods for dealing with database
    private ConnectionData billCon = new ConnectionData();
    
    // declare object for class Customer to set and get values of Item
    private User user;
     // declare object for class Item to set and get values of Item
    private Items items;
    // declare object for class Item to set and get values of Item
    private Category category;
    // declare object for class Item to set and get values of Item
    private Order order;
    // declare object for class Item to set and get values of Item
    private Bill bill;
    
    private static ArrayList <Items> itemsList;
    private static ArrayList <Category> categoryList;
    private static ArrayList <User> userList;
    private static ArrayList <Order> orderList;
    private static ArrayList <Bill> billList;
    
    public String email;
    public static double grandTotal = 0;
    public double itemsPrice = 0;
    public static double itemsTotal = 0;
    public static int quantityOrder = 0;
    public static int stockQuantity = 0;
    public double cash = 0;
    public double change = 0;
    
    /**
     * Creates new form OrderForm
     */
    public OrderForm() {
        initComponents();
    }
    
    public OrderForm(String userEmail) {
        initComponents();
        orderCon.ID_order();
        txtQuantity.setValue(1);
        showDate();
        showTime();
        grandTotal = 0;
        email = userEmail;
    }
    
    public void showDate() {
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dd = sdf.format(date);
        txtDate.setText(dd);
    }
    
    public void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date dt = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
                txtTime.setText(sdf.format(dt));
            }
        }).start();
    }
    
    public void itemsNameByCategory(String category) {
        DefaultTableModel tableContent = (DefaultTableModel) itemTable.getModel();
        tableContent.setRowCount(0);
        
        ArrayList<Items> itemsList = itemsCon.readAllItemsByCategory(category);
        Iterator<Items> itemsItr = itemsList.iterator();
        
        Object rowData[] = new Object[2];
        
        // use repetition structure to read all item attributes of the ArrayList
        // and display the data in the table according to the columns and row
        for(Items x:itemsList){
            rowData[0] = x.getTitle();
            rowData[1] = x.getQuantity();
            tableContent.addRow(rowData);
        }
    }
    
    // Method definition: Reset the form
    public void clearForm(){
        txtID.setText("ID");
        txtTitle.setText("Album Title");
        txtPrice.setText("Price");
        txtQuantity.setValue(1);
        txtItemsTotal.setText("Total Price");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelExit = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        buttonAdd = new javax.swing.JButton();
        comboBoxCategory = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel18 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        buttonClear = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        billTable = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        buttonPay = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        buttonExact = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(75, 0, 130));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.setEditable(false);
        txtName.setBackground(new java.awt.Color(75, 0, 130));
        txtName.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtName.setBorder(null);
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 90, 30));

        txtEmail.setEditable(false);
        txtEmail.setBackground(new java.awt.Color(75, 0, 130));
        txtEmail.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEmail.setBorder(null);
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 142, 30));

        labelExit.setBackground(new java.awt.Color(255, 255, 255));
        labelExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelExit.setForeground(new java.awt.Color(255, 255, 255));
        labelExit.setText("X");
        labelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExitMouseClicked(evt);
            }
        });
        jPanel1.add(labelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 10, 20, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user 35.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 40, 40));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 50));

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator5.setForeground(new java.awt.Color(75, 0, 130));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 180, 10));

        txtID.setEditable(false);
        txtID.setBackground(new java.awt.Color(204, 255, 255));
        txtID.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtID.setForeground(new java.awt.Color(75, 0, 130));
        txtID.setText("ID");
        txtID.setBorder(null);
        jPanel4.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 180, 30));

        txtTitle.setEditable(false);
        txtTitle.setBackground(new java.awt.Color(204, 255, 255));
        txtTitle.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(75, 0, 130));
        txtTitle.setText("Album Title");
        txtTitle.setBorder(null);
        jPanel4.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 180, 30));

        jSeparator3.setForeground(new java.awt.Color(75, 0, 130));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 180, 10));

        txtPrice.setEditable(false);
        txtPrice.setBackground(new java.awt.Color(204, 255, 255));
        txtPrice.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(75, 0, 130));
        txtPrice.setText("Price");
        txtPrice.setBorder(null);
        jPanel4.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 180, 30));

        jSeparator4.setForeground(new java.awt.Color(75, 0, 130));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 180, 10));

        buttonAdd.setBackground(new java.awt.Color(75, 0, 130));
        buttonAdd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonAdd.setForeground(new java.awt.Color(240, 240, 240));
        buttonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add (White).png"))); // NOI18N
        buttonAdd.setText("Add to Cart");
        buttonAdd.setBorder(null);
        buttonAdd.setBorderPainted(false);
        buttonAdd.setIconTextGap(10);
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });
        jPanel4.add(buttonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 130, 40));

        comboBoxCategory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comboBoxCategory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxCategoryItemStateChanged(evt);
            }
        });
        comboBoxCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCategoryActionPerformed(evt);
            }
        });
        jPanel4.add(comboBoxCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 200, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(75, 0, 130));
        jLabel1.setText("Quantity");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 70, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(75, 0, 130));
        jLabel9.setText("ID");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 60, 30));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(75, 0, 130));
        jLabel16.setText("Album Title");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, 30));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(75, 0, 130));
        jLabel17.setText("Price");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, 30));

        itemTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(itemTable);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 310, 290));

        txtCategoryID.setEditable(false);
        txtCategoryID.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.add(txtCategoryID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 40, 30));

        txtQuantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtQuantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtQuantityStateChanged(evt);
            }
        });
        jPanel4.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 200, 30));

        txtItemsTotal.setEditable(false);
        txtItemsTotal.setBackground(new java.awt.Color(204, 255, 255));
        txtItemsTotal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtItemsTotal.setForeground(new java.awt.Color(75, 0, 130));
        txtItemsTotal.setText("Total Price");
        txtItemsTotal.setBorder(null);
        jPanel4.add(txtItemsTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 180, 30));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(75, 0, 130));
        jLabel18.setText("Total");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 70, 30));

        jSeparator11.setForeground(new java.awt.Color(75, 0, 130));
        jPanel4.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 180, 10));

        buttonClear.setBackground(new java.awt.Color(75, 0, 130));
        buttonClear.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonClear.setForeground(new java.awt.Color(240, 240, 240));
        buttonClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear (White).png"))); // NOI18N
        buttonClear.setText("Clear");
        buttonClear.setBorder(null);
        buttonClear.setBorderPainted(false);
        buttonClear.setIconTextGap(10);
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });
        jPanel4.add(buttonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 110, 40));

        jPanel9.setBackground(new java.awt.Color(75, 0, 130));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Items");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 40));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 330, 700));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Category ID", "Name", "Price", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(orderTable);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 570, 300));

        jPanel8.setBackground(new java.awt.Color(75, 0, 130));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Order");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 610, 370));

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        billTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Email", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(billTable);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 570, 250));

        jPanel10.setBackground(new java.awt.Color(75, 0, 130));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sells List");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 40));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 610, 320));

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(75, 0, 130));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Change");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(75, 0, 130));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Total");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(75, 0, 130));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Cash");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 100, -1));

        buttonPay.setBackground(new java.awt.Color(75, 0, 130));
        buttonPay.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonPay.setForeground(new java.awt.Color(240, 240, 240));
        buttonPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cash.png"))); // NOI18N
        buttonPay.setText("   Pay");
        buttonPay.setBorder(null);
        buttonPay.setBorderPainted(false);
        buttonPay.setIconTextGap(10);
        buttonPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPayActionPerformed(evt);
            }
        });
        jPanel6.add(buttonPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 310, 40));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(75, 0, 130));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Quantity");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, -1));

        txtQuantityOrder.setEditable(false);
        txtQuantityOrder.setBackground(new java.awt.Color(204, 255, 255));
        txtQuantityOrder.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtQuantityOrder.setForeground(new java.awt.Color(75, 0, 130));
        txtQuantityOrder.setText("Order Quantity ");
        txtQuantityOrder.setBorder(null);
        jPanel6.add(txtQuantityOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 190, 30));

        jSeparator7.setForeground(new java.awt.Color(75, 0, 130));
        jPanel6.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 190, 10));

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(204, 255, 255));
        txtTotal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(75, 0, 130));
        txtTotal.setText("Total Price");
        txtTotal.setBorder(null);
        jPanel6.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 190, 30));

        jSeparator8.setForeground(new java.awt.Color(75, 0, 130));
        jPanel6.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 190, 10));

        txtCash.setBackground(new java.awt.Color(204, 255, 255));
        txtCash.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCash.setForeground(new java.awt.Color(75, 0, 130));
        txtCash.setText("Enter Cash");
        txtCash.setBorder(null);
        txtCash.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCashFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCashFocusLost(evt);
            }
        });
        jPanel6.add(txtCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 190, 30));

        jSeparator9.setForeground(new java.awt.Color(75, 0, 130));
        jPanel6.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 190, 10));

        txtChange.setEditable(false);
        txtChange.setBackground(new java.awt.Color(204, 255, 255));
        txtChange.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtChange.setForeground(new java.awt.Color(75, 0, 130));
        txtChange.setText("Your Change");
        txtChange.setBorder(null);
        jPanel6.add(txtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 190, 30));

        jSeparator10.setForeground(new java.awt.Color(75, 0, 130));
        jPanel6.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 190, 10));

        buttonExact.setBackground(new java.awt.Color(75, 0, 130));
        buttonExact.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonExact.setForeground(new java.awt.Color(240, 240, 240));
        buttonExact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/equal.png"))); // NOI18N
        buttonExact.setText("Exact");
        buttonExact.setBorder(null);
        buttonExact.setBorderPainted(false);
        buttonExact.setIconTextGap(10);
        buttonExact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExactActionPerformed(evt);
            }
        });
        jPanel6.add(buttonExact, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 310, 40));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 60, 370, 370));

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTime.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtTime.setForeground(new java.awt.Color(75, 0, 130));
        txtTime.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel7.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 180, 30));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(75, 0, 130));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Order ID :");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, -1));

        jPanel11.setBackground(new java.awt.Color(75, 0, 130));

        txtDate.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtDate.setForeground(new java.awt.Color(255, 255, 255));
        txtDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDate.setText("Date");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 40));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(75, 0, 130));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Time      :");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 110, -1));

        txtOrderID.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtOrderID.setForeground(new java.awt.Color(75, 0, 130));
        txtOrderID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel7.add(txtOrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 180, 30));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 440, 370, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseClicked
        int a = JOptionPane.showConfirmDialog(null,"Do you want to logout?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_labelExitMouseClicked

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        String itemID = txtID.getText();
        String categoryID = txtCategoryID.getText();
        String title = txtTitle.getText();
        String price = txtPrice.getText();
        int index = itemTable.getSelectedRow();
        if(itemID.equals("ID") || title.equals("Album Title") || price.equals("Price"))
        {
            JOptionPane.showMessageDialog(null, "Please select the item!");
        }
        else
        {
            orderCon.addToCartItems();
            clearForm();
        }
    }//GEN-LAST:event_buttonAddActionPerformed

    private void itemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemTableMouseClicked
        clearForm();
        int index = itemTable.getSelectedRow();
        TableModel model = itemTable.getModel();
        String itemsTitle = model.getValueAt(index, 0).toString();
        Items items = itemsCon.getItemsByTitle(itemsTitle);
        txtID.setText(items.getItemID());
        txtCategoryID.setText(items.getCategoryID());
        txtTitle.setText(items.getTitle());
        txtPrice.setText(items.getPrice());
        txtItemsTotal.setText("RM " +items.getPrice());
        itemsPrice = Double.parseDouble(items.getPrice());
        itemsTotal = Double.parseDouble(items.getPrice());
    }//GEN-LAST:event_itemTableMouseClicked

    private void comboBoxCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCategoryActionPerformed
        String category = txtCategoryID.getText().trim();
        itemsNameByCategory(category);
    }//GEN-LAST:event_comboBoxCategoryActionPerformed

    private void orderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderTableMouseClicked
        int index = orderTable.getSelectedRow();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to remove this item?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            TableModel model = orderTable.getModel();
            String total = model.getValueAt(index, 5).toString();
            String amount = model.getValueAt(index, 4).toString();
            grandTotal = grandTotal - Double.parseDouble(total);
            quantityOrder -= Integer.parseInt(amount);
            txtTotal.setText(String.valueOf(grandTotal).format("%.2f", grandTotal));
            txtQuantityOrder.setText(String.valueOf(quantityOrder));
            ((DefaultTableModel) orderTable.getModel()).removeRow(index);
        }
    }//GEN-LAST:event_orderTableMouseClicked

    private void buttonPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPayActionPerformed
        if (txtChange.getText().equals("Your Change"))
        {
            JOptionPane.showMessageDialog(null, "Please click Exact button!");
        }
        else
        {
            bill = new Bill();

            bill.setOrderID(txtOrderID.getText().trim());
            bill.setEmail(txtEmail.getText().trim());
            bill.setQuantity(txtQuantityOrder.getText().trim());
            bill.setTotal(txtTotal.getText().trim());
            bill.setCash(txtCash.getText().trim());
            bill.setChange(txtChange.getText().trim());
            bill.setDate(txtDate.getText().trim());
            bill.setTime(txtTime.getText().trim());
            
            DefaultTableModel dtm = (DefaultTableModel) OrderForm.orderTable.getModel();
            //int index = dtm.getRowCount();
            /*
            for (int i = 0; i < dtm.getRowCount(); i++) 
            {
                bill = new Bill();
                bill.setOrderID(OrderForm.txtOrderID.getText().trim());
                bill.setItemID(dtm.getValueAt(i, 0).toString());
                bill.setQuantity(dtm.getValueAt(i, 3).toString());
                bill.setSubTotal(dtm.getValueAt(i, 4).toString());
                bill.setEmail(OrderForm.txtEmail.getText().trim());
            }*/
            
            // call method to save the order
            itemsCon.updateStock();
            billCon.saveOrder(bill);
            orderCon.saveItem_Order();
            new ReceiptForm().setVisible(true);

            ReceiptForm.TxtBill.setText(ReceiptForm.TxtBill.getText() + "Order Id: " + "\t" + txtOrderID.getText() + "\n");
            ReceiptForm.TxtBill.setText(ReceiptForm.TxtBill.getText() + "Date: " + "\t" + txtDate.getText() + "\n");
            ReceiptForm.TxtBill.setText(ReceiptForm.TxtBill.getText() + "Time: " + "\t" + txtTime.getText() + "\n");
            ReceiptForm.TxtBill.setText(ReceiptForm.TxtBill.getText() + "Seller Name: " + "\t" + txtName.getText() + "\n");
            ReceiptForm.TxtBill.setText(ReceiptForm.TxtBill.getText() + "\n==============================================================\n");
            ReceiptForm.TxtBill.setText(ReceiptForm.TxtBill.getText() + "\t                          Order Details\n\n");
            ReceiptForm.TxtBill.setText(ReceiptForm.TxtBill.getText() + "Title" + "\t\t" + "Price" + "\t" + "Quantity" + "\t" + "Total" + "\n");
            for (int i = 0; i < dtm.getRowCount(); i++) 
            {
                String title = dtm.getValueAt(i, 2).toString();
                String price = dtm.getValueAt(i, 3).toString();
                String quantity = dtm.getValueAt(i, 4).toString();
                String subTotal = dtm.getValueAt(i, 5).toString();
                ReceiptForm.TxtBill.setText(ReceiptForm.TxtBill.getText() + title + "\t" + price + "\t" + quantity + "\t" + subTotal + "\n");
            }
            ReceiptForm.TxtBill.setText(ReceiptForm.TxtBill.getText() + "\n");
            ReceiptForm.TxtBill.setText(ReceiptForm.TxtBill.getText() + "Total: " + "\t" + txtTotal.getText() + "\n");
            ReceiptForm.TxtBill.setText(ReceiptForm.TxtBill.getText() + "Quantity: " + "\t" + txtQuantityOrder.getText() + "\n");
            ReceiptForm.TxtBill.setText(ReceiptForm.TxtBill.getText() + "Cash: " + "\t" + txtCash.getText() + "\n");
            ReceiptForm.TxtBill.setText(ReceiptForm.TxtBill.getText() + "Change: " + "\t" + txtChange.getText() + "\n");

            ReceiptForm.TxtBill.setText(ReceiptForm.TxtBill.getText() + "\n==============================================================\n");
            ReceiptForm.TxtBill.setText(ReceiptForm.TxtBill.getText() + "\t              Thankyou, please visit again!\n");
            
            setVisible(false);
            // call method to generate auto increment order id
            orderCon.ID_order();
            new OrderForm().setVisible(true);
            grandTotal = 0;
        }
    }//GEN-LAST:event_buttonPayActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        clearForm();
    }//GEN-LAST:event_buttonClearActionPerformed

    private void txtCashFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCashFocusGained
        if (txtCash.getText().equals("Enter Cash"))
        {
            txtCash.setText("");
        }
    }//GEN-LAST:event_txtCashFocusGained

    private void txtCashFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCashFocusLost
        if (txtCash.getText().equals(""))
        {
            txtCash.setText("Enter Cash");
        }
    }//GEN-LAST:event_txtCashFocusLost

    private void comboBoxCategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxCategoryItemStateChanged
        String categoryName = (String)comboBoxCategory.getSelectedItem();
        Category category = categoryCon.getCategoryByName(categoryName);
        txtCategoryID.setText(category.getCategoryID());
    }//GEN-LAST:event_comboBoxCategoryItemStateChanged

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        ArrayList<Category> categoryList = categoryCon.readAllCategory();
        Iterator<Category> categoryItr = categoryList.iterator();
        
        while (categoryItr.hasNext()) {
            Category x = categoryItr.next();
            comboBoxCategory.addItem(x.getName());
        }
        String category = (String) comboBoxCategory.getSelectedItem();
        itemsNameByCategory(category);
        
        orderCon.readAllOrderSeller();
    }//GEN-LAST:event_formComponentShown

    private void txtQuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtQuantityStateChanged
        int quantity = (Integer) txtQuantity.getValue();
        if (quantity <= 1) {
            txtQuantity.setValue(1);
            quantity = 1;
        }
        itemsTotal = itemsPrice * quantity;
        txtItemsTotal.setText(String.valueOf(itemsTotal).format("%.2f", itemsTotal));
    }//GEN-LAST:event_txtQuantityStateChanged

    private void buttonExactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExactActionPerformed
        double cash = Double.parseDouble(txtCash.getText());
        change = cash - grandTotal;
        if(cash < grandTotal)
        {
            double change2 = grandTotal - cash;
            JOptionPane.showMessageDialog(null, "The cash not enough RM " + change2 + "!");
            txtChange.setText("Your Change");
        }
        else
        {
            txtChange.setText("RM " +String.valueOf(change).format("%.2f", change));
        }
    }//GEN-LAST:event_buttonExactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable billTable;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonExact;
    private javax.swing.JButton buttonPay;
    private javax.swing.JComboBox<String> comboBoxCategory;
    public static final javax.swing.JTable itemTable = new javax.swing.JTable();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel labelExit;
    public static final javax.swing.JTable orderTable = new javax.swing.JTable();
    public static final javax.swing.JTextField txtCash = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtCategoryID = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtChange = new javax.swing.JTextField();
    public static final javax.swing.JLabel txtDate = new javax.swing.JLabel();
    public static final javax.swing.JTextField txtEmail = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtID = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtItemsTotal = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtName = new javax.swing.JTextField();
    public static final javax.swing.JLabel txtOrderID = new javax.swing.JLabel();
    public static final javax.swing.JTextField txtPrice = new javax.swing.JTextField();
    public static final javax.swing.JSpinner txtQuantity = new javax.swing.JSpinner();
    public static final javax.swing.JTextField txtQuantityOrder = new javax.swing.JTextField();
    public static final javax.swing.JLabel txtTime = new javax.swing.JLabel();
    public static final javax.swing.JTextField txtTitle = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtTotal = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables
}
