/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.utem.musicstore;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.io.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;
import java.text.*;
/**
 *
 * @author User
 */
public class SellersForm extends javax.swing.JFrame {
    
    // declare object for class AddNewProduct to use methods for dealing with database
    private ConnectionData userCon = new ConnectionData();
    
    // declare object for class Item to set and get values of Item
    private User user;
    
    private static ArrayList <User> userList;
    /**
     * Creates new form SellersForm
     */
    public SellersForm() {
        initComponents();
    }
    
    // Method definition: Reset the form
    public void clearForm(){
        txtName.setText("Enter Name");
        txtEmail.setText("Enter Email");
        txtPassword.setText("Enter Password");
        labelError.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelExit = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSeller = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txtEmail = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        buttonAdd = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        labelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(290, 0));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1070, 780));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(75, 0, 130));
        jLabel1.setText("Sellers");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        labelExit.setBackground(new java.awt.Color(255, 255, 255));
        labelExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelExit.setForeground(new java.awt.Color(75, 0, 130));
        labelExit.setText("X");
        labelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExitMouseClicked(evt);
            }
        });
        jPanel1.add(labelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 11, 20, -1));

        tableSeller.setBackground(new java.awt.Color(75, 0, 130));
        tableSeller.setBorder(new javax.swing.border.MatteBorder(null));
        tableSeller.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tableSeller.setForeground(new java.awt.Color(255, 255, 255));
        tableSeller.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSeller.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSellerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSeller);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 970, 480));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(75, 0, 130));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/name.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 30));

        txtName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtName.setForeground(new java.awt.Color(75, 0, 130));
        txtName.setText("Enter Name");
        txtName.setBorder(null);
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 220, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 220, 10));

        txtEmail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(75, 0, 130));
        txtEmail.setText("Enter Email");
        txtEmail.setBorder(null);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 220, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 220, 10));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(75, 0, 130));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/email.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(75, 0, 130));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/password.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 30, 30));

        txtPassword.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(75, 0, 130));
        txtPassword.setText("Enter Password");
        txtPassword.setBorder(null);
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 220, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 220, 10));

        buttonAdd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonAdd.setForeground(new java.awt.Color(75, 0, 130));
        buttonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        buttonAdd.setText("Add");
        buttonAdd.setBorder(null);
        buttonAdd.setBorderPainted(false);
        buttonAdd.setIconTextGap(10);
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 110, 40));

        buttonUpdate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonUpdate.setForeground(new java.awt.Color(75, 0, 130));
        buttonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.png"))); // NOI18N
        buttonUpdate.setText("Update");
        buttonUpdate.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        buttonUpdate.setBorderPainted(false);
        buttonUpdate.setIconTextGap(10);
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(buttonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 110, 40));

        buttonDelete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonDelete.setForeground(new java.awt.Color(75, 0, 130));
        buttonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        buttonDelete.setText("Delete");
        buttonDelete.setBorder(null);
        buttonDelete.setBorderPainted(false);
        buttonDelete.setIconTextGap(10);
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(buttonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 110, 40));

        buttonClear.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonClear.setForeground(new java.awt.Color(75, 0, 130));
        buttonClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear.png"))); // NOI18N
        buttonClear.setText("Clear");
        buttonClear.setBorder(null);
        buttonClear.setBorderPainted(false);
        buttonClear.setIconTextGap(10);
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });
        jPanel1.add(buttonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 110, 40));

        labelError.setFont(new java.awt.Font("Segoe UI Variable", 1, 11)); // NOI18N
        labelError.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(labelError, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 310, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseClicked
        // Close form
        setVisible(false);
    }//GEN-LAST:event_labelExitMouseClicked

    private void tableSellerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSellerMouseClicked
        int index = tableSeller.getSelectedRow();
        TableModel model = tableSeller.getModel();
        String name = model.getValueAt(index, 0).toString();
        txtName.setText(name);
        String email = model.getValueAt(index, 1).toString();
        txtEmail.setText(email);
        String password = model.getValueAt(index, 2).toString();
        txtPassword.setText(password);
    }//GEN-LAST:event_tableSellerMouseClicked

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        if (txtEmail.getText().equals("Enter Email"))
        {
            txtEmail.setText("");
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if (txtEmail.getText().equals(""))
        {
                txtEmail.setText("Enter Email");
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        if (txtPassword.getText().equals("Enter Password"))
        {
            txtPassword.setText("");
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if (txtPassword.getText().equals(""))
        {
            txtPassword.setText("Enter Password");
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        String name = txtName.getText();
        String email = txtEmail.getText();
        String password = txtPassword.getText();

        // Check wether the form are completed or empty
        if(!name.equals("Enter Name") && !email.equals("Enter Email") && !password.equals("Enter Password"))
        {
            JOptionPane.showMessageDialog(null, "Successfully saved.");
            user = new User();

            user.setName(txtName.getText().trim());
            user.setEmail(txtEmail.getText().trim());
            user.setPassword(txtPassword.getText().trim());

            // call method to add
            userCon.saveUser(user);
            userCon.updateSellerType(txtEmail.getText().trim(), user);
            userCon.countAllSeller();

            setVisible(false);
            new SellersForm().setVisible(true);
        }
        else if(name.equals("Enter Name") && email.equals("Enter Email") && password.equals("Enter Password"))
        {
            labelError.setText("Fields are empty!");
        }
        else if(name.equals("Enter Name"))
        {
            labelError.setText("Name is empty!");
        }
        else if(email.equals("Enter Email"))
        {
            labelError.setText("Email is empty!");
        }
        else if(password.equals("Enter Password"))
        {
            labelError.setText("Password is empty!");
        }
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        String name = txtName.getText();
        String email = txtEmail.getText();
        String password = txtPassword.getText();
        String type = ("Seller");

        // Check wether the form are completed or empty
        if(!name.equals("Enter Name") && !email.equals("Enter Email") && !password.equals("Enter Password"))
        {
            user = new User();

            user.setName(txtName.getText().trim());
            user.setEmail(txtEmail.getText().trim());
            user.setPassword(txtPassword.getText().trim());
            user.setType(type);

            // call method to update the car based on car register id
            userCon.updateSeller(txtEmail.getText().trim(), user);
            userCon.countAllSeller();

            // message to inform user
            JOptionPane.showMessageDialog(null, "The user has been updated!");

            setVisible(false);
            new SellersForm().setVisible(true);
        }
        else if(name.equals("Enter Name") && email.equals("Enter Email") && password.equals("Enter Password"))
        {
            labelError.setText("Fields are empty!");
        }
        else if(name.equals("Enter Name"))
        {
            labelError.setText("Name is empty!");
        }
        else if(email.equals("Enter Email"))
        {
            labelError.setText("Email is empty!");
        }
        else if(password.equals("Enter Password"))
        {
            labelError.setText("Password is empty!");
        }
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        String name = txtName.getText();
        String email = txtEmail.getText();
        String password = txtPassword.getText();
        String type = ("Seller");

        // Check wether the form are completed or empty
        if(!name.equals("Enter Name") && !email.equals("Enter Email") && !password.equals("Enter Password"))
        {
            // Display confirmation message box to delete the item
            int result = JOptionPane.showConfirmDialog(null, "Are you sure to delete this user?", "Delete User",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

            if (result == JOptionPane.YES_OPTION) {

                //call method to delete the category based on category number
                userCon.deleteSeller(txtEmail.getText().trim());
                userCon.countAllSeller();

                // Reset the form
                setVisible(false);
                new SellersForm().setVisible(true);
            }
        }
        else if(name.equals("Enter Name") && email.equals("Enter Email") && password.equals("Enter Password"))
        {
            labelError.setText("Fields are empty!");
        }
        else if(name.equals("Enter Name"))
        {
            labelError.setText("Name is empty!");
        }
        else if(email.equals("Enter Email"))
        {
            labelError.setText("Email is empty!");
        }
        else if(password.equals("Enter Password"))
        {
            labelError.setText("Password is empty!");
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        // Call method to reset the form
        clearForm();
    }//GEN-LAST:event_buttonClearActionPerformed

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        if (txtName.getText().equals("Enter Name"))
        {
            txtName.setText("");
        }
    }//GEN-LAST:event_txtNameFocusGained

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        if (txtName.getText().equals(""))
        {
            txtName.setText("Enter Name");
        }
    }//GEN-LAST:event_txtNameFocusLost

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // Call method readAll() to fetch all data from database
        userList = userCon.readAllSeller();
        
        DefaultTableModel tableContent = (DefaultTableModel) tableSeller.getModel();
        
        Object rowData[] = new Object[3];
        
        // use repetition structure to read all item attributes of the ArrayList
        // and display the data in the table according to the columns and row
        for(User x:userList){
            rowData[0] = x.getName();
            rowData[1] = x.getEmail();
            rowData[2] = x.getPassword();
            tableContent.addRow(rowData);
        }
    }//GEN-LAST:event_formComponentShown

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel labelExit;
    private javax.swing.JTable tableSeller;
    private javax.swing.JTextField txtEmail;
    public static final javax.swing.JTextField txtName = new javax.swing.JTextField();
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
