/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.utem.carrental;

import javax.swing.JOptionPane;
import java.io.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;
import java.text.*;
/**
 *
 * @author kemal
 */
public class ManageCar extends javax.swing.JFrame {
    // declare object for class AddNewProduct to use methods for dealing with database
    private Connection carCon = new Connection();
    
    // declare object for class AddNewProduct to use methods for dealing with database
    //private Connection carCon = new Connection();
    
    // declare object for class Item to set and get values of Item
    private Car car;
    
    private static ArrayList <Car> carList;
    /**
     * Creates new form ManageProduct
     */
    public ManageCar() {
        initComponents();
        carCon.id_car();
        // Call method to determine initial save button state
        //btnUpdate.setEnabled(false);
        //btnDelete.setEnabled(false);
    }
    
    // Method definition: Check wether the form are completed or empty
    //public void validateField(){
    //    String registerId = TxtRegisterId.getText();
    //    String name = TxtSeatQuantity.getText();
     //   String seatQuantity = TxtSeatQuantity.getText();
     //   String price = TxtPrice.getText();
        // Check each field are empty
     //   if(!registerId.equals("") && !name.equals("") && !price.equals("") && !seatQuantity.equals("")){
            // if empty, return true
      //      btnUpdate.setEnabled(true);
      //  }
     //   else{
            // if complete, return false
      //      btnUpdate.setEnabled(false);
      //  }
    //}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtRegisterId = new javax.swing.JTextField();
        TxtSeatQuantity = new javax.swing.JTextField();
        TxtName = new javax.swing.JTextField();
        TxtPrice = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        validateAll = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        carTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setLocation(new java.awt.Point(350, 134));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Register ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Seat Quantity:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        TxtRegisterId.setEditable(false);
        TxtRegisterId.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(TxtRegisterId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 340, -1));
        getContentPane().add(TxtSeatQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 340, -1));
        getContentPane().add(TxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 340, -1));
        getContentPane().add(TxtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 340, -1));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_icon.jpeg"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 30, 40, 40));

        btnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-new-34.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 110, 40));

        btnClear.setBackground(new java.awt.Color(0, 0, 0));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-eraser-34.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, -1, -1));

        btnDelete.setBackground(new java.awt.Color(0, 0, 0));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-trash-34.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 110, 40));

        btnSave.setBackground(new java.awt.Color(0, 0, 0));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-save-as-34.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 340, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("MANAGE CAR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 240, -1));

        validateAll.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        validateAll.setForeground(new java.awt.Color(255, 255, 102));
        getContentPane().add(validateAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 320, 30));

        carTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        carTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Register ID", "Name", "Seat Quantity", "Price", "Status"
            }
        ));
        carTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(carTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 480, 377));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroundcar.jpg"))); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(1040, 540));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // Close form
        setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // Reset the form
        setVisible(false);
        new ManageCar().setVisible(true);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String registerId = TxtRegisterId.getText();
        String name = TxtSeatQuantity.getText();
        String seatQuantity = TxtSeatQuantity.getText();
        String price = TxtPrice.getText();
        
        // Check wether the form are completed or empty
        if(!registerId.equals("") && !name.equals("") && !seatQuantity.equals("") && !price.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Successfully saved.");
            car = new Car();
            
            car.setRegisterId(TxtRegisterId.getText().trim());
            car.setName(TxtName.getText().trim());
            car.setSeatQuantity(TxtSeatQuantity.getText().trim());
            car.setPrice(TxtPrice.getText().trim());

            // call method to update the car based on car register id
            carCon.updateCar(TxtRegisterId.getText().trim(), car);

            setVisible(false);
            new ManageCar().setVisible(true);
        }
        else if(registerId.equals("") && name.equals("") && seatQuantity.equals("") && price.equals(""))
        {
            validateAll.setText("Field(s) are empty!!!");
        }
        else if(registerId.equals(""))
        {
            validateAll.setText("Register ID's field is empty!");
        }
        else if(name.equals(""))
        {
            validateAll.setText("Name's field is empty!");
        }
        else if(seatQuantity.equals(""))
        {
            validateAll.setText("Seat Quantity's field is empty!");
        }
        else
        {
            validateAll.setText("Price's field is empty!");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // Call method readAll() to fetch all data from database
        carList = carCon.readAllCar();
        
        DefaultTableModel tableContent = (DefaultTableModel) carTable.getModel();
        
        Object rowData[] = new Object[5];
        
        // use repetition structure to read all item attributes of the ArrayList
        // and display the data in the table according to the columns and row
        for(Car x:carList){
            rowData[0] = x.getRegisterId();
            rowData[1] = x.getName();
            rowData[2] = x.getSeatQuantity();
            rowData[3] = x.getPrice();
            rowData[4] = x.getStatus();
            tableContent.addRow(rowData);
        }
    }//GEN-LAST:event_formComponentShown

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String registerId = TxtRegisterId.getText();
        String name = TxtSeatQuantity.getText();
        String seatQuantity = TxtSeatQuantity.getText();
        String price = TxtPrice.getText();
        
        // Check wether the form are completed or empty
        if(!registerId.equals("") && !name.equals("") && !seatQuantity.equals("") && !price.equals(""))
        {
            // Display confirmation message box to delete the item
            int result = JOptionPane.showConfirmDialog(null, "Are you sure to delete the item?", "Delete Item",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (result == JOptionPane.YES_OPTION) {

                //call method to delete the category based on category number
                carCon.deleteCar(TxtRegisterId.getText().trim());

                //display message
                JOptionPane.showMessageDialog(null, "The item has been deleted!");

                // Reset the form
                setVisible(false);
                new ManageCar().setVisible(true);
        }
        }
        else if(registerId.equals("") || name.equals("") || seatQuantity.equals("") || price.equals(""))
        {
            //display message
            JOptionPane.showMessageDialog(null, "Please complete the form!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String registerId = TxtRegisterId.getText();
        String name = TxtSeatQuantity.getText();
        String seatQuantity = TxtSeatQuantity.getText();
        String price = TxtPrice.getText();
        
        // Check wether the form are completed or empty
        if(!registerId.equals("") && !name.equals("") && !seatQuantity.equals("") && !price.equals(""))
        {
            car = new Car();
            
            car.setRegisterId(TxtRegisterId.getText().trim());
            car.setName(TxtName.getText().trim());
            car.setSeatQuantity(TxtSeatQuantity.getText().trim());
            car.setPrice(TxtPrice.getText().trim());
            
            // call method to update the item based on item number
            carCon.saveCar(car);
            
            carCon.id_car();

            setVisible(false);
            new ManageCar().setVisible(true);
        }
        else if(registerId.equals("") && name.equals("") && seatQuantity.equals("") && price.equals(""))
        {
            validateAll.setText("Field(s) are empty!!!");
        }
        else if(registerId.equals(""))
        {
            validateAll.setText("Register ID's field is empty!");
        }
        else if(name.equals(""))
        {
            validateAll.setText("Name's field is empty!");
        }
        else if(seatQuantity.equals(""))
        {
            validateAll.setText("Seat Quantity's field is empty!");
        }
        else
        {
            validateAll.setText("Price's field is empty!");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void carTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carTableMouseClicked
        int index = carTable.getSelectedRow();
        TableModel model = carTable.getModel();
        
        String registerId = model.getValueAt(index, 0).toString();
        TxtRegisterId.setText(registerId);
        
        String name = model.getValueAt(index, 1).toString();
        TxtName.setText(name);
        
        String seatQuantity = model.getValueAt(index, 2).toString();
        TxtSeatQuantity.setText(seatQuantity);
        
        String price = model.getValueAt (index, 3).toString();
        TxtPrice.setText(price);
        
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
    }//GEN-LAST:event_carTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtName;
    private javax.swing.JTextField TxtPrice;
    public static javax.swing.JTextField TxtRegisterId;
    private javax.swing.JTextField TxtSeatQuantity;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTable carTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel validateAll;
    // End of variables declaration//GEN-END:variables
}
