/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.utem.carrental;

import javax.swing.JOptionPane;
import java.io.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;
import java.text.*;
import java.util.Random;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
/**
 *
 * @author User
 */
public class OrderCar extends javax.swing.JFrame {
    // declare object for class ItemManager to use methods for dealing with database
    private Connection carCon = new Connection();
    private Connection customerCon = new Connection();
    private Connection orderCon = new Connection();
    
    // declare object for class Car to set and get values of Item
    private Car car;
    
    private static ArrayList <Car> carList;
    
    // declare object for class Customer to set and get values of Item
    private Customer customer;
    
    private static ArrayList <Customer> customerList;
    
    // declare object for class Order to set and get values of Item
    private Order order;
    
    private static ArrayList <Order> orderList;
    
    // declare object for class Order to set and get values of Item
    private ReturnOrder returnOrder;
    
    private static ArrayList <ReturnOrder> returnOrderList;
    
    public int grandTotal = 0;
    public int carPrice = 0;
    public int carTotal = 0;
    
    /**
     * Creates new form OrderCar
     */
    public OrderCar() {
        initComponents();
        
        Random random = new Random();
        int newID = random.nextInt(10000, 99999);
        TxtOrderId.setText("O" + Integer.toString(newID));
        
        Date date = new Date();

        TxtDate.getJCalendar().setMinSelectableDate(date);
        TxtDateReturn.getJCalendar().setMinSelectableDate(TxtDate.getJCalendar().getDate());
        
        TxtCarRegisterId.setEditable(false);
        TxtCarName.setEditable(false);
        TxtCarSeatQuantity.setEditable(false);
        TxtCarPrice.setEditable(false);
        TxtCarTotal.setEditable(false);
        TxtCarStatus.setEditable(false);
    }
    
    public void carNameByCategory(String car) {
        DefaultTableModel tableContent = (DefaultTableModel) carTable.getModel();
        tableContent.setRowCount(0);
        
        ArrayList<Car> carList = carCon.readAllCar();
        Iterator<Car> carItr = carList.iterator();
        
        Object rowData[] = new Object[1];
        
        // use repetition structure to read all item attributes of the ArrayList
        // and display the data in the table according to the columns and row
        for(Car x:carList){
            rowData[0] = x.getName();
            tableContent.addRow(rowData);
        }
    }
    
    public void clearForm() {
        TxtCarRegisterId.setText("");
        TxtCarName.setText("");
        TxtCarSeatQuantity.setText("");
        TxtCarPrice.setText("");
        TxtCarPeriod.setText("");
        TxtCarTotal.setText("");
        TxtCarStatus.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtCarPrice = new javax.swing.JTextField();
        TxtCarSeatQuantity = new javax.swing.JTextField();
        TxtCarName = new javax.swing.JTextField();
        TxtCarTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        carTable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        validateAll = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        TxtDate = new com.toedter.calendar.JDateChooser();
        TxtDateReturn = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        TxtCarStatus = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        TxtCarPeriod = new javax.swing.JTextField();
        btnGenerate = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 50, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone Number:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 120, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Address:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 80, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Email:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 50, -1));

        TxtAddress.setEditable(false);
        getContentPane().add(TxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 330, -1));

        TxtPhoneNumber.setEditable(false);
        getContentPane().add(TxtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 330, -1));

        TxtName.setEditable(false);
        getContentPane().add(TxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 330, -1));

        TxtEmail.setEditable(false);
        getContentPane().add(TxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 330, -1));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_icon.jpeg"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 40, 40, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("RENT YOUR CAR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Register ID:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, 80, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Name:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Seat Quantity:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 280, 100, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Status:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 280, -1, -1));
        getContentPane().add(TxtCarPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, 230, -1));
        getContentPane().add(TxtCarSeatQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 310, 230, -1));
        getContentPane().add(TxtCarName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 240, 230, -1));
        getContentPane().add(TxtCarRegisterId, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 240, 230, -1));

        TxtCarTotal.setEditable(false);
        TxtCarTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(TxtCarTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 520, 230, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Date Book:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 420, -1, -1));

        carTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        carTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        carTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(carTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 230, 470));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 102));
        jLabel14.setText("*Click on the car name to select");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 660, 230, -1));

        btnClear.setBackground(new java.awt.Color(0, 0, 0));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-eraser-34.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 620, 230, 40));

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 204));
        jLabel12.setText("Customer Information");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 260, -1));

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 204));
        jLabel13.setText("Car Information");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, 230, -1));

        btnSave.setBackground(new java.awt.Color(0, 0, 0));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-save-as-34.png"))); // NOI18N
        btnSave.setText("Submit & Print Receipt");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 620, 230, 40));

        validateAll.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        validateAll.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(validateAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 710, 710, 50));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Order ID:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 350, 70, -1));

        TxtOrderId.setEditable(false);
        TxtOrderId.setName(""); // NOI18N
        getContentPane().add(TxtOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 380, 230, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Total:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 490, 43, -1));
        getContentPane().add(TxtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 450, 230, -1));
        getContentPane().add(TxtDateReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 450, 230, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Period(Days):");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 490, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Date Return:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 420, -1, -1));
        getContentPane().add(TxtCarStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 310, 230, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Price:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 350, -1, -1));

        TxtCarPeriod.setEditable(false);
        TxtCarPeriod.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(TxtCarPeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 520, 230, 30));

        btnGenerate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGenerate.setForeground(new java.awt.Color(153, 0, 0));
        btnGenerate.setText("^^Generate Period & Total^^");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 560, 510, 40));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroundcar.jpg"))); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1700, 1300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // Close form
        setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void carTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carTableMouseClicked
        int index = carTable.getSelectedRow();
        TableModel model = carTable.getModel();
        String carName = model.getValueAt(index, 0).toString();
        Car car = carCon.getCarByName(carName);
        TxtCarRegisterId.setText(car.getRegisterId());
        TxtCarName.setText(car.getName());
        TxtCarSeatQuantity.setText(car.getSeatQuantity());
        TxtCarPrice.setText(car.getPrice());
        TxtCarPeriod.getText();
        TxtCarTotal.setText(car.getPrice());
        TxtCarStatus.setText(car.getStatus());
        carPrice = Integer.parseInt(car.getPrice());
        carTotal = Integer.parseInt(car.getPrice());
    }//GEN-LAST:event_carTableMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String orderId = TxtOrderId.getText();
        String registerId = TxtCarRegisterId.getText();
        String email = TxtEmail.getText();
        String period = String.valueOf(TxtCarPeriod.getText());
        String status = TxtCarStatus.getText();
        String totaltxt = TxtCarTotal.getText();
        
        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        String bookingDate = dFormat.format(TxtDate.getDate());
        String returnDate = dFormat.format(TxtDateReturn.getDate());
        String billDate = dFormat.format(date);
        
        Date bookDate = TxtDate.getDate();
        Date retDate = TxtDateReturn.getDate();
        
        long difference = retDate.getTime() - bookDate.getTime();

        long diffInDays = (long) (difference / 1000 / 60 / 60 / 24);

        long day = diffInDays;
        
        // Check wether the form are completed or empty
        if(!orderId.equals("") && !registerId.equals("") && !email.equals("") && !period.equals("") && !bookingDate.equals("") && !returnDate.equals("") && !totaltxt.equals(""))
        {
            if(day <= 0)
            {
                JOptionPane.showMessageDialog(null, "Your return date can't be low than your book date!!!");
            }
            else
            {
                order = new Order();

                order.setOrderId(TxtOrderId.getText().trim());
                order.setRegisterId(TxtCarRegisterId.getText().trim());
                order.setEmail(TxtEmail.getText().trim());
                order.setDate(bookingDate.trim());
                order.setReturnDate(returnDate.trim());
                order.setPeriod(TxtCarPeriod.getText().trim());
                order.setTotal(TxtCarTotal.getText().trim());

                returnOrder = new ReturnOrder();

                returnOrder.setOrderId(TxtOrderId.getText().trim());
                returnOrder.setRegisterId(TxtCarRegisterId.getText().trim());
                returnOrder.setEmail(TxtEmail.getText().trim());
                returnOrder.setDate(bookingDate.trim());
                returnOrder.setReturnDate(returnDate.trim());
                returnOrder.setPeriod(TxtCarPeriod.getText().trim());
                returnOrder.setTotal(TxtCarTotal.getText().trim());

                if (status.equals("Booked")) 
                {
                    JOptionPane.showMessageDialog(null, "This car are not available!");
                } 
                else 
                {
                    new BillForm().setVisible(true);
                    // call method to save the order
                    orderCon.saveOrder(order, returnOrder);
                    
                    BillForm.TxtBill.setText(BillForm.TxtBill.getText() + "       Order Id: " + "\t" + TxtOrderId.getText() + "\n");
                    BillForm.TxtBill.setText(BillForm.TxtBill.getText() + "       Date: " + "\t" + billDate + "\n");
                    BillForm.TxtBill.setText(BillForm.TxtBill.getText() + "       Name: " + "\t" + TxtName.getText() + "\n");
                    BillForm.TxtBill.setText(BillForm.TxtBill.getText() + "       \n==========================================================\n");
                    BillForm.TxtBill.setText(BillForm.TxtBill.getText() + "       \t                   Order Details\n\n");
                    
                    BillForm.TxtBill.setText(BillForm.TxtBill.getText() + "       Car Name: " +      "\t\t" + TxtCarName.getText() + "\n");
                    BillForm.TxtBill.setText(BillForm.TxtBill.getText() + "       Seat Quantity: " + "\t" + TxtCarSeatQuantity.getText() + "\n");
                    BillForm.TxtBill.setText(BillForm.TxtBill.getText() + "       Booking Date: " + "\t" + bookingDate + "\n");
                    BillForm.TxtBill.setText(BillForm.TxtBill.getText() + "       Return Date: " + "\t" + returnDate + "\n");
                    BillForm.TxtBill.setText(BillForm.TxtBill.getText() + "       Period: " +        "\t\t" + TxtCarPeriod.getText() + "\n");

                    BillForm.TxtBill.setText(BillForm.TxtBill.getText() + "       \n==========================================================\n");
                    BillForm.TxtBill.setText(BillForm.TxtBill.getText() + "       Total Paid (Rm): " + "\t" + TxtCarTotal.getText() + "\n");
                    BillForm.TxtBill.setText(BillForm.TxtBill.getText() + "       \n==========================================================\n");
                    BillForm.TxtBill.setText(BillForm.TxtBill.getText() + "       \t          Thankyou, please visit again!\n");
                    // call method to generate auto increment order id
                    //orderCon.id_order();
                    car = new Car();

                    // call method to update the car based on car register id
                    carCon.updateCarStatus(TxtCarRegisterId.getText().trim(), car);

                    setVisible(false);
                    Random random = new Random();
                    int newID = random.nextInt(10000, 99999);
                    TxtOrderId.setText("O" + Integer.toString(newID));
                }
            }
        }
        else
        {
            validateAll.setText("Field(s) are empty!!! Please add a car to proceed.");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // Call method readAll() to fetch all data from database
        carList = carCon.readAllCar();
        
        DefaultTableModel tableContent = (DefaultTableModel) carTable.getModel();
        
        Object rowData[] = new Object[5];
        
        // use repetition structure to read all item attributes of the ArrayList
        // and display the data in the table according to the columns and row
        for(Car x:carList){
            rowData[0] = x.getName();
            tableContent.addRow(rowData);
        }
    }//GEN-LAST:event_formComponentShown

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
        //Date startDate = TxtDateBook.getDate();
        Date bookDate = TxtDate.getDate();
        Date returnDate = TxtDateReturn.getDate();
        
        long difference = returnDate.getTime() - bookDate.getTime();

        int diffInDays = (int) (difference / 1000 / 60 / 60 / 24);

        //TxtFine.setText(String.valueOf(diffInDays));
        int period = diffInDays;

        TxtCarPeriod.setText(String.valueOf(period));


        carTotal = Integer.parseInt(TxtCarTotal.getText().trim());
        carTotal = carPrice * period;
        TxtCarTotal.setText(String.valueOf(carTotal));
    }//GEN-LAST:event_btnGenerateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderCar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JTextField TxtAddress = new javax.swing.JTextField();
    private javax.swing.JTextField TxtCarName;
    private javax.swing.JTextField TxtCarPeriod;
    private javax.swing.JTextField TxtCarPrice;
    public static final javax.swing.JTextField TxtCarRegisterId = new javax.swing.JTextField();
    private javax.swing.JTextField TxtCarSeatQuantity;
    private javax.swing.JTextField TxtCarStatus;
    private javax.swing.JTextField TxtCarTotal;
    private com.toedter.calendar.JDateChooser TxtDate;
    private com.toedter.calendar.JDateChooser TxtDateReturn;
    public static final javax.swing.JTextField TxtEmail = new javax.swing.JTextField();
    public static final javax.swing.JTextField TxtName = new javax.swing.JTextField();
    public static final javax.swing.JTextField TxtOrderId = new javax.swing.JTextField();
    public static final javax.swing.JTextField TxtPhoneNumber = new javax.swing.JTextField();
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnSave;
    private javax.swing.JTable carTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel validateAll;
    // End of variables declaration//GEN-END:variables
}
