/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.utem.rentalsystem;

import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class CarDelete extends javax.swing.JFrame 
{
        private CarManager manage = new CarManager();
        private static ArrayList<Car> carList;
          
        private Car car;
    /**
     * Creates new form DeleteCar
     */
    public CarDelete() {
        initComponents();
        // call method to determine buttons state
        initialBtn();
    }
    
    private void initialBtn(){
        deleteBtn.setEnabled(false);
        resetBtn.setEnabled(false);
    }
    
    private void clearForm(){
        regTxtField.setText("");
        nameTxtField.setText("");
        priceTxtField.setText("");
        qtyTxtField.setText("");
        statusCB.setSelectedIndex(0);
    }
    
    private boolean isEmptyField(){
        if(regTxtField.getText().isEmpty() || nameTxtField.getText().isEmpty() || priceTxtField.getText().isEmpty() || qtyTxtField.getText().isEmpty() || statusCB.getSelectedIndex()== -1)
        {
            //if empty, return true
            return true;
        }
        else
        {
            //if empty, return false
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        qtyTxtField = new javax.swing.JTextField();
        statusCB = new javax.swing.JComboBox<>();
        deleteBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        resetBtn = new javax.swing.JButton();
        nameTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        searcBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        priceTxtField = new javax.swing.JTextField();
        regTxtField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Delete Car Page");
        setResizable(false);

        jLabel5.setText("Seat Quantity :");

        jLabel3.setText("Car Name :");

        qtyTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtyTxtFieldKeyPressed(evt);
            }
        });

        statusCB.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        statusCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Booked", "Available" }));

        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        deleteBtn.setText("Delete Car");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Car Availability :");

        resetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset.png"))); // NOI18N
        resetBtn.setText("Reset Form");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        nameTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameTxtFieldKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel1.setText("DELETE CAR");

        searcBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        searcBtn.setText("Search Car");
        searcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searcBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Price (RM) :");

        jLabel2.setText("Car Registration No :");

        priceTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                priceTxtFieldKeyPressed(evt);
            }
        });

        regTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                regTxtFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(327, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(344, 344, 344))
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(searcBtn)
                .addGap(34, 34, 34)
                .addComponent(deleteBtn)
                .addGap(31, 31, 31)
                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(regTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qtyTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusCB, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(searcBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
         // Display confirmation message box to delete the car
        int result = JOptionPane.showConfirmDialog(null,"Are you sure to delete the car?", "Delete Car",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
       
        // if user choose Yes
        if(result == JOptionPane.YES_OPTION) {
            // Call method to delete the item based on car registration number
            manage.deleteCar(regTxtField.getText().trim());

            //display message to inform user
            JOptionPane.showMessageDialog(null, "The car has been deleted!");
            
            // Call method to reset the form
            clearForm();

            // Call method to set initial buttons state
            initialBtn();
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // Call method to reset the form
        clearForm();
        // Call method to set initial butttons state
        initialBtn();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void searcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searcBtnActionPerformed
        //create new car object to receive input
        car = new Car();

        //create object to set two -decimal places of price output format
        DecimalFormat df = new DecimalFormat("0.00");

        // Check if the Car No field is empty
        if(regTxtField.getText().isEmpty()){
            // Display information message box
            JOptionPane.showMessageDialog(null, "Please enter Car Registration No");
        }
        // If Car No field is not empty
        else{
            //call method to search the car based on car registration number
            //then return the found car
            car = manage.searchCar(regTxtField.getText().trim());

            //if item found
            if(car.getVehicleReg() != null)
            {
                //Display the car attributes in the form
                regTxtField.setText(String.valueOf(car.getVehicleReg()));
                nameTxtField.setText(car.getVehicleName());
                qtyTxtField.setText(String.valueOf(car.getSeatQuantity()));
                priceTxtField.setText(String.valueOf(df.format(car.getPrice())));
                statusCB.setSelectedItem(String.valueOf(car.getVehicleStatus()));

                // Set the new state buttons
                deleteBtn.setEnabled(true);
                resetBtn.setEnabled(true);

            }
            // If do not found the selected car yet
            else{
                // Call method to set initial buttons state
                initialBtn();
                // Call method to reset the form
                clearForm();
                // Display information message box
                JOptionPane.showMessageDialog(null, "Car does not exist!");
            }
        }
    }//GEN-LAST:event_searcBtnActionPerformed

    private void regTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regTxtFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        nameTxtField.requestFocus();
    }//GEN-LAST:event_regTxtFieldKeyPressed

    private void nameTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTxtFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        qtyTxtField.requestFocus();
    }//GEN-LAST:event_nameTxtFieldKeyPressed

    private void qtyTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyTxtFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        priceTxtField.requestFocus();
    }//GEN-LAST:event_qtyTxtFieldKeyPressed

    private void priceTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceTxtFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        statusCB.requestFocus();
    }//GEN-LAST:event_priceTxtFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JTextField priceTxtField;
    private javax.swing.JTextField qtyTxtField;
    private javax.swing.JTextField regTxtField;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton searcBtn;
    private javax.swing.JComboBox<String> statusCB;
    // End of variables declaration//GEN-END:variables

}
