/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.utem.rentalsystem;

import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class CarSave extends javax.swing.JFrame 
{
        private CarManager manage = new CarManager();
        private static ArrayList<Car> carList;
          
        private Car car;

    /**
     * Creates new form ManageCar
     */
    public CarSave() {
        initComponents();
        
        // call method to determine buttons state
        initialBtn();
    }
    
    private void initialBtn(){
        editBtn.setEnabled(false);
        saveBtn.setEnabled(true);
        resetBtn.setEnabled(false);
    }
    
    private void clearForm(){
        regTxtField.setText("");
        nameTxtField.setText("");
        priceTxtField.setText("");
        qtyTxtField.setText("");
        statusCB.setSelectedIndex(0);
    }
    
    private boolean isEmptyField(){
        if(regTxtField.getText().isEmpty() || nameTxtField.getText().isEmpty() || priceTxtField.getText().isEmpty() || qtyTxtField.getText().isEmpty() || statusCB.getSelectedIndex()== -1)
        {
            //if empty, return true
            return true;
        }
        else
        {
            //if empty, return false
            return false;
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qtyTxtField = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        regTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        priceTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        statusCB = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();
        searcBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Save Car Page");
        setResizable(false);

        qtyTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtyTxtFieldKeyPressed(evt);
            }
        });

        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        saveBtn.setText("Save Car");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        resetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset.png"))); // NOI18N
        resetBtn.setText("Reset Form");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel1.setText("Car Details");

        jLabel2.setText("Car Registration No :");

        regTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                regTxtFieldKeyPressed(evt);
            }
        });

        jLabel3.setText("Car Name :");

        nameTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameTxtFieldKeyPressed(evt);
            }
        });

        jLabel4.setText("Price (RM) :");

        priceTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                priceTxtFieldKeyPressed(evt);
            }
        });

        jLabel5.setText("Seat Quantity :");

        statusCB.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        statusCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Booked", "Available" }));
        statusCB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                statusCBKeyPressed(evt);
            }
        });

        jLabel7.setText("Car Availability :");

        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        editBtn.setText("Edit Car");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        searcBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        searcBtn.setText("Search Car");
        searcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searcBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(searcBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(regTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(qtyTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusCB, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searcBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // Check if the form is completed
        if(!isEmptyField()){
            // Create new car object to receive input
            car = new Car();

            // Call methods at class Car to set the new value from the form
            car.setVehicleReg(regTxtField.getText().trim());
            car.setVehicleName(nameTxtField.getText().trim());
            car.setPrice(Double.parseDouble(priceTxtField.getText().trim()));
            car.setSeatQuantity(Integer.parseInt(qtyTxtField.getText().trim()));
            car.setVehicleStatus(statusCB.getSelectedItem().toString().trim());
            //call method to save the car
            manage.saveCar(car);

            //display information message box
            JOptionPane.showMessageDialog(null,"Car added succesfully!");
            clearForm();
        }
        //If the form is not completed yet
        else{
            // Display information message box
            JOptionPane.showMessageDialog(null, "Complete the form!");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // Call method to reset the form
        clearForm();
        // Call method to set initial butttons state
        initialBtn();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
                //Check if the form is completed
        if(!isEmptyField()){
                    // call setter to assign car attributes with the values from GUI
                    car = new Car();
                    car.setVehicleName(nameTxtField.getText().trim());
                    car.setPrice(Double.parseDouble(priceTxtField.getText().trim()));
                    car.setSeatQuantity(Integer.parseInt(qtyTxtField.getText().trim()));
                    car.setVehicleStatus(statusCB.getSelectedItem().toString().trim());
                    
                    //call method to update the car based on car registration number
                    manage.editCar(regTxtField.getText().trim(), car);
                    
                    //message to infrom user
                    JOptionPane.showMessageDialog(null,"Car has been updated!");
                    //Call method to set initial buttons state
                    initialBtn();
                    
                    // Call method to reset the form
                    clearForm();
                    
                }
                //if the form is not completed yet
                else{
            
                    // Display information message box
                    JOptionPane.showMessageDialog(null, "Complete the form!");
        }                                      
    }//GEN-LAST:event_editBtnActionPerformed

    private void searcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searcBtnActionPerformed
        //create new car object to receive input
        car = new Car();
        
        //create object to set two -decimal places of price output format
        DecimalFormat df = new DecimalFormat("0.00");

        // Check if the Car No field is empty
        if(regTxtField.getText().isEmpty()){
            // Display information message box
            JOptionPane.showMessageDialog(null, "Please enter Registration No");
        }
        // If Car No field is not empty
        else{
                //call method to search the car based on car registration number
                //then return the found car
                car = manage.searchCar(regTxtField.getText().trim());
                
                //if item found
                if(car.getVehicleReg() != null)
                {
                    //Display the car attributes in the form
                    regTxtField.setText(String.valueOf(car.getVehicleReg()));
                    nameTxtField.setText(car.getVehicleName());
                    qtyTxtField.setText(String.valueOf(car.getSeatQuantity()));
                    priceTxtField.setText(String.valueOf(df.format(car.getPrice())));
                    statusCB.setSelectedItem(String.valueOf(car.getVehicleStatus()));
                    
                    // Set the new state buttons
                    saveBtn.setEnabled(false);
                    editBtn.setEnabled(true);
                    resetBtn.setEnabled(true);
                  
                }
                // If do not found the selected car yet
                else{
                // Call method to set initial buttons state
                initialBtn();
                // Call method to reset the form
                clearForm();
                // Display information message box
                JOptionPane.showMessageDialog(null, "Car does not exist!");
            }
        }
    }//GEN-LAST:event_searcBtnActionPerformed

    private void regTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regTxtFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        nameTxtField.requestFocus();
    }//GEN-LAST:event_regTxtFieldKeyPressed

    private void nameTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTxtFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        qtyTxtField.requestFocus();
    }//GEN-LAST:event_nameTxtFieldKeyPressed

    private void qtyTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyTxtFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        priceTxtField.requestFocus();
    }//GEN-LAST:event_qtyTxtFieldKeyPressed

    private void statusCBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_statusCBKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        statusCB.requestFocus();
    }//GEN-LAST:event_statusCBKeyPressed

    private void priceTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceTxtFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        statusCB.requestFocus();
    }//GEN-LAST:event_priceTxtFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarSave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarSave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarSave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarSave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarSave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JTextField priceTxtField;
    private javax.swing.JTextField qtyTxtField;
    private javax.swing.JTextField regTxtField;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searcBtn;
    private javax.swing.JComboBox<String> statusCB;
    // End of variables declaration//GEN-END:variables

}
